name: release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build .deb
        run: |
          set -e
          ./build-deb.sh

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            whatsapp-waydroid_*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
